### ISSUE TITLE
Is not working on ATOM 1.17.2 x64

### ISSUE THREAD

**Issue by Jerajo** [olmokramer/atom-autohide-tree-view#90]
Uncaught (in promise) TypeError: pkg.mainModule.createView is not a function
    at file:///C:/Users/.atom/packages/autohide-tree-view/lib/main.js:23:31

**Comment by concon121** [comment]
Getting the same error printed to the console.  Atom version: 1.20.1

**Comment by OmgImAlexis** [comment]
Same issue here with version `1.22.1`.

```
Uncaught (in promise) TypeError: pkg.mainModule.createView is not a function
```

**Comment by x-hannibal** [comment]
Same issue with version `1.27.2`
```
Uncaught (in promise) TypeError: pkg.mainModule.createView is not a function
```

**Comment by rislah** [comment]
Same, not working

**Comment by sanarena** [comment]
I've created this simple package to be able do my daily tasks without file tree annoyance for now, far from original plugin but it just works: https://atom.io/packages/filetree-autohide

**Comment by olmokramer** [comment]
Hi everyone, I'm sorry for the extremely late reply. As you have probably noticed I've stopped maintaining my Atom plugins a few years ago. I got very frustrated with how Atom was maintained and started ignoring all of my plugins. I'm sorry for that. I won't install Atom to test and mergeer PRs, but I'd be happy to transfer my repositories to anyone that wants to maintain any of my plugins. Again, I'm sorry.
